import { ExamenFisicoCompleto } from "@/app/types/examenFisico";

export const getEmptyExamenFisico = (): ExamenFisicoCompleto => ({
    antecedentesPersonales: {
        delMedioYLaborales: {
            residenciaActual: "",
            residenciasAnteriores: "",
        },
        habitos: {
            estudios: "",
            ocupacion: "",
            alcoholYToxicos: "",
            alimentacionHabitosAlimenticiosYVenenos: "",
            sexualidad: "",
            deportes: "",
            catarsis: "",
            tabaco: "",
            otrasAdicciones: "",
        },
        patologicos: {
            infectoContagiosas: "",
            vacunas: "",
            cardiovasculares: "",
            gastrointestinales: "",
            respiratorias: "",
            urinarias: "",
            hematologicos: "",
            alergicos: "",
            quirurgicosYTraumatologicos: "",
            dermatologicos: "",
            oftalmologicos: "",
        },
        ginecologicos: {
            quirurgicos: "",
            menarca: "",
            ritmo: "",
            fum: "",
            abortos: "",
            gestas: "",
            partos: "",
        },
        familiares: {
            anticoncepcion: "",
            antecedetesFamiliares: "",
            hijos: "",
        },
    },
    piel: {
        coloracion: "",
        humedad: "",
        temperatura: "",
        elasticidad: "",
        unas: "",
        distribucionPilosa: "",
        cicatrices: "",
    },
    tejidoCelularSubcutaneo: {
        distribucion: "",
        cantidad: "",
        nodulos: "",
        enfisema: "",
        edemas: "",
    },
    sistemaLinfatico: {
        linfangitis: "",
        adenomegalias: "",
    },
    sistemaOsteoArticuloMuscular: {
        musculo: "",
        huesos: "",
        columnaVertebral: "",
        indiceTobilloBrazoDerecha: "",
        indiceTobilloBrazoIzquierda: "",
        perimetroDistalProximalMD: "",
        perimetroDistalProximalMI: "",
        articulaciones: "",
    },
    cabeza: {
        forma: "",
        tamano: "",
        ojos: "",
        pupilas: "",
        conjuntivas: "",
        corneas: "",
        escleroticas: "",
        parpados: "",
        fosasNasales: "",
        boca: "",
        labios: "",
        encias: "",
        fauces: "",
        lengua: "",
        dientes: "",
        glandulasSalivales: "",
        pabellonesAuricularesCAE: "",
    },
    cuello: {
        conformacion: "",
        laringe: "",
        huecoSupraclavicular: "",
        huecoInfraclavicular: "",
        yugulares: "",
        tiroides: "",
    },
    sistemaVenoso: {
        varices: "",
        flebitis: "",
        trombosis: "",
        circulacionColateral: "",
    },
    mamas: {
        inspeccion: {
            tamano: "",
            superficie: "",
            areolas: "",
            pezones: "",
            maniobrapectorales: "",
            pielRetraccion: false,
            elevacion: false,
            deNaranja: false,
            ulceras: false,
            observaciones: "",
        },
        palpacion: {
            limites: "",
            dolorosa: "",
            superficie: "",
            consistencia: "",
            tumor: "",
            fluacionPiel: "",
            derramePorPezon: "",
        },
    },
    aparatoRespiratorio: {
        torax: "",
        forma: "",
        elasticidad: "",
        tipoRespiratorio: "",
        expansionDeVertices: "",
        vibracionesVocales: "",
        expansionDeBases: "",
        percusion: "",
        auscultacion: "",
        observaciones: "",
    },
    aparatoCardiovascular: {
        frecuenciaCardiaca: "",
        central: "",
        periferica: "",
        pulsoradialCaracteristicas: "",
        rellenoCapilar: "",
        latidoApexiano: "",
        latidosPalpables: "",
        r1: "",
        r2: "",
        rudosAgregados: "",
        frotes: "",
        soplos: "",
        observaciones: "",
    },
    abdomen: {
        inspeccion: "",
        palpacion: "",
        superficial: "",
        profunda: "",
        percusion: "",
        higado: "",
        limiteSup: "",
        limiteInf: "",
        altura: "",
        caracteristicas: "",
        auscultacion: "",
        rha: "",
        soplos: "",
        celdaEsplenica: "",
        bazo: "",
        perimetro: "",
        observaciones: "",
    },
    aparatoUrogenital: {
        genitalesExternos: "",
        tactoVaginal: "",
        tactoRectal: "",
        punoPercusion: "",
        puntosUretrales: "",
        observaciones: "",
    },
    examenGinecologico: {
        montedevenus: "",
        labiosMayoresMenores: "",
        clitoris: "",
        introito: "",
        vagina: "",
        fondoSacoVaginal: "",
        cervix: "",
        utero: "",
        anexos: "",
        examenAbVaRe: "",
        especuloscopia: "",
        observaciones: "",
    },
    examenObstetrico: {
        au: "",
        lcf: "",
        mfa: "",
        du: "",
        tono: "",
        leopold: "",
        tactoVaginal: "",
        bishopP: "",
        bishopR: "",
        bishopE: "",
        bishopL: "",
        bishopD: "",
        membranasOvulares: "",
        maniobraDeTamer: "",
        plano: "",
        pelvimetria: "",
        hidrorrea: "",
        ginecorragia: "",
        loquios: "",
        retraccion: "",
        mamas: "",
        lactancia: "",
        perine: "",
        especuloscopia: "",
        tbm: "",
        diagnostico: "",
    },
    sistemaNervioso: {
        conciencia: "",
        marcha: "",
        tonoMuscular: "",
        fuerzaMuscular: "",
        signosPiramidales: "",
        sensibilidadSuperficial: "",
        signosMeningeos: "",
        paresCraneanos: "",
        taxia: "",
        praxia: "",
    },
    signosVitales: {
        pa: "",
        fc: "",
        fr: "",
        tax: "",
        glucemia: "",
        impresionGeneral: "",
        facie: "",
        decubito: "",
        marcha: "",
        talla: "",
        pesoActual: "",
        pesoHabitual: "",
        estadoNutricional: "",
    },
    examenOftalmologico: {
        fondoDeOjo: "",
        mediosBirefringentes: "",
        cruces: "",
        relacion: "",
        hemorragiaExudados: "",
    },
    electrocardiograma: {
        ritmo: "",
        frecuencia: "",
        pr: "",
        qt: "",
        ondapEje: "",
        duracion: "",
        amplitud: "",
        conformacion: "",
        qrsEje: "",
        duracionQrs: "",
        ondat: "",
        st: "",
        conclusiones: "",
    },
    radiografiaTorax: {
        tecnica: "",
        partesBlandas: "",
        partesOseas: "",
        hemidiafragmas: "",
        ict: "",
        senosCostofrenicos: "",
        mediastino: "",
        siluetaCardiovascular: "",
        hilios: "",
        camposPulmonares: "",
        conclusiones: "",
        laboratorio: "",
    },
    impresionDiagnostica: {
        impresionDiagnostica: "",
        comentarioDeIngreso: "",
    },
    planDiagnostico: {
        a: "",
        b: "",
        c: "",
        d: "",
        e: "",
        f: "",
        g: "",
        h: "",
        i: "",
        j: "",
        k: "",
    },
    planTerapeutico: {
        pt1: "",
        pt2: "",
        pt3: "",
        pt4: "",
        pt5: "",
        pt6: "",
        pt7: "",
        pt8: "",
        pt9: "",
        pt10: "",
        pt11: "",
        pt12: "",
        pt13: "",
        pt14: "",
        pt15: "",
    },
    examenesComplementarios: {
        detalle: "",
    },
});
